### ISSUE TITLE
Would you mind licensing project?

### ISSUE THREAD

**Issue by StVirtan** [OpenDyslexic/opendyslexic-chrome#13]
Hello,
Would you be agreeable to license this project under GNU v2?
Context to why I want this:
I work for a large company, and want to make this extension available to them. Currently they can't use it because of the required permission to read/modify data on all websites due to the security concerns of that permission. So, I want to make an internal fork of this extension, but I can't unless it is under and open source license like GNU v2.

On Github, Code without an explicit license is protected by copyright and is by default All Rights Reserved. The person or people who wrote the code are protected as such.

**Comment by RobertJGabriel** [comment]
@antijingoist bump

**Comment by antijingoist** [comment]
Sorry this took so long.

What license options are there here? I'd rather not do GNU. 
(If you need permission for an internal fork, go ahead, by all means).

**Comment by StVirtan** [comment]
Hello!

No worries at all :) Thanks for getting back to me. Any OSI-license would be suitable https://opensource.org/licenses

https://choosealicense.com/ can help you pick if you are unsure about them.

While I would personally be happy with just your verbal permission, it's sadly not enough for our legal department.

Thanks,

**Comment by antijingoist** [comment]
tagging @RobertJGabriel  because this will affect him too:

Do you have a preference on license? I would go with MIT otherwise.

**Comment by RobertJGabriel** [comment]
Sorry just saw this. I would go with MIT aswell.

**Comment by RobertJGabriel** [comment]
Will add it to the readme now

**Comment by RobertJGabriel** [comment]
Hey this is officially in the readme now :) cc @StVirtan

**Comment by sillywilly42** [comment]
I'm sorry to bother you with this, but would you mind adding a LICENSE file, or approving my Pull Request to do so: https://github.com/OpenDyslexic/opendyslexic-chrome/pull/23
