### ISSUE TITLE
BBC example no longer applicable with OpenDyslexic

### ISSUE THREAD

**Issue by grahamperrin** [OpenDyslexic/opendyslexic-chrome#19]
Firefox 60.0.1 on FreeBSD-CURRENT: 

![2018-06-01 16 04 40 browsers](https://user-images.githubusercontent.com/192271/40848274-a07a0aca-65b6-11e8-9f1b-9c1bc295a996.png)

```text
$ pkg info firefox | grep Version
Version        : 60.0.1_3,1
$ date ; uname -v
Fri  1 Jun 2018 16:10:30 BST
FreeBSD 12.0-CURRENT #3 r334382: Thu May 31 01:37:12 BST 2018     root@momh167-gjp4-hpelitebook8570p-freebsd:/usr/obj/usr/src/amd64.amd64/sys/GENERIC 
```

With Mobile Dyslexic in lieu of OpenDyslexic: 

![2018-06-01 16 05 36 browsers](https://user-images.githubusercontent.com/192271/40848321-c4f20ac4-65b6-11e8-89c4-f16e7923f8bf.png)

Any ideas? 

Cheers

**Comment by RobertJGabriel** [comment]
Im currently working on this.

We have a firefox repo too. https://github.com/OpenDyslexic/firefox-extension

**Comment by grahamperrin** [comment]
Thank you 👍 

(I was in the other repo a few days ago for `https://github.com/OpenDyslexic/firefox-extension/issues/1`; apologies for the misplacement here.)

**Comment by RobertJGabriel** [comment]
Hey @grahamperrin this is sorted and released now

**Comment by RobertJGabriel** [comment]
<img width="1212" alt="screen shot 2018-06-05 at 11 31 24 pm" src="https://user-images.githubusercontent.com/6218780/41017281-e1c63eb6-6919-11e8-84cf-487a9ce60261.png">

**Comment by grahamperrin** [comment]
Fix confirmed. Thanks 👍
