### ISSUE TITLE
Plugin causes dark themes to go white (on some sites)

### ISSUE THREAD

**Issue by Eros** [OpenDyslexic/opendyslexic-chrome#21]
Using the dark theme for twitter caused the entire page to go white with the plugin installed
https://i.imgur.com/7NO9cPu.png
Turning the plugin off fixed the issue, only seems to be on twitters base website, stuff like tweetdeck is completely fine

**Comment by RobertJGabriel** [comment]
Thanks for reporting, going to look into this later but its a good task for anyone who wishes to try there hand at it.

**Comment by RobertJGabriel** [comment]
Hey @Eros 

I have updated the project with a fix and will get this out later today hopefully.
