### ISSUE TITLE
Feature request - ability to disable the extension for specific websites

### ISSUE THREAD

**Issue by c-okelly** [OpenDyslexic/opendyslexic-chrome#22]
Less of an issue and more of a feature request. 

What do you think about the idea of allowing user to specify domains where the plugin would be disabled.

**Comment by RobertJGabriel** [comment]
This is a nice idea. Will look into adding  this to the roadmap

**Comment by RobertJGabriel** [comment]
Hey @c-okelly sorry for the delay. A nice way would to be have a tabbed section. With a textarea input. The user enters a new url per line. We store this in chromes api storage and check it if it needs to be enabled of not. I will follow up with a more in detail example. I love the idea.

**Comment by c-okelly** [comment]
Would you be happy about adding a separate library for handling the urls and url matching? Probably this one => [url-patter](https://www.npmjs.com/package/url-pattern)
