### ISSUE TITLE
PDFs

### ISSUE THREAD

**Issue by MaryAnnMullet** [OpenDyslexic/opendyslexic-chrome#25]
OpenDyslexic font doesn't seem to work in a pdf that is open in the browser. This extension could be amazing in a school setting, but all of the textbooks and workbooks are pdfs, and I can't get them to use the font.

**Comment by RobertJGabriel** [comment]
Hey @MaryAnnMullet ,

Thank you for the issue and the suggestion. I have looked into this and it is possible using a third party PDF viewer.
Going to tag this under version 8.0.0 as I like this a lot but will need a lot of testing first 💃
