### ISSUE TITLE
Ed2d Law

### ISSUE THREAD

**Issue by swarner12** [OpenDyslexic/opendyslexic-chrome#35]
Is the OpenDyslexic Chrome Extension compliant with New York's Ed2D law?

**Comment by RobertJGabriel** [comment]
@swarner12 it sure is and if you have any questions. I will love to answer them.

**Comment by swarner12** [comment]
Can you send me the documents regarding the NYSEd2d law compliance?
Thank you for your help,

Sarah Warner
Assistive Technology Consultant
Monroe 2-Orleans BOCES
585.617.2318
